# Generated by Django 4.0.3 on 2022-03-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
